name: Build Windows

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        release: false
        update: false
        install: >-
          base-devel
          git
          mingw-w64-x86_64-nodejs
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-make
          mingw-w64-x86_64-curl
          mingw-w64-x86_64-freetype
          mingw-w64-x86_64-giflib
          mingw-w64-x86_64-libjpeg-turbo
          mingw-w64-x86_64-libpng
          mingw-w64-x86_64-libwebp
          mingw-w64-x86_64-pixman
          mingw-w64-x86_64-SDL2
          mingw-w64-x86_64-SDL2_image
          mingw-w64-x86_64-tinyxml2
          mingw-w64-x86_64-zlib
          mingw-w64-x86_64-libarchive

    - shell: msys2 {0}
      run: |
        cd LibreSprite_2.0_A_STUDI0/LibreSprite-master
        git clone https://github.com/aseprite/flic.git src/flic
        git clone https://github.com/aseprite/simpleini.git third_party/simpleini
        git clone https://github.com/LibreSprite/duktape.git third_party/duktape
        mkdir build
        cd build
        cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DUSE_V8_SANDBOX=OFF ..
        make -j 4

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: LibreSprite-2.0-Windows
        path: LibreSprite_2.0_A_STUDI0/LibreSprite-master/build/bin/
